# Generated by Django 5.2.3 on 2025-06-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todos",
            new_name="Todo",
        ),
    ]
